# Generated by Django 5.2.9 on 2025-12-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applies_to_brands',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.brand'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_regions',
            field=models.ManyToManyField(blank=True, to='products.region'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_stores',
            field=models.ManyToManyField(blank=True, to='products.store'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.coupon'),
        ),
    ]
