# Generated by Django 5.2.9 on 2025-12-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusModel',
        ),
    ]
