# Generated by Django 5.2.9 on 2025-12-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_line_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='reason',
            field=models.CharField(blank=True, choices=[('CUSTOMER_BUSY', 'Khách bận/Hẹn lại'), ('UNREACHABLE', 'Thuê bao/Không nghe máy'), ('WRONG_ADDRESS', 'Sai thông tin/Địa chỉ'), ('REFUSED', 'Khách từ chối nhận hàng'), ('OTHER', 'Lý do khác (Thời tiết,...)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Giao không thành công'), ('RESCHEDULED', 'Đã hẹn lại lịch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Đang đóng gói'), ('READY_TO_PICK', 'Chờ lấy hàng'), ('SHIPPED', 'Đang vận chuyển'), ('DELIVERED', 'Giao thành công'), ('RETURNED', 'Đã hoàn hàng'), ('FAILED', 'Giao thất bại')], default='PREPARING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('CANCELED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
    ]
