# Generated by Django 5.2.9 on 2025-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_final_total_amount_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=21, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
