# Generated by Django 5.2.9 on 2025-12-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryattempt',
            name='reason',
            field=models.CharField(blank=True, choices=[('CUSTOMER_BUSY', 'Khách bận/Hẹn lại'), ('UNREACHABLE', 'Khách không nghe máy'), ('WRONG_ADDRESS', 'Sai thông tin/Địa chỉ'), ('REFUSED', 'Khách từ chối nhận hàng'), ('OTHER', 'Lý do khác (Thời tiết,...)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('PROCESSING', 'Đang xử lý'), ('PROCESSING_SUCCESS', 'Xử lý thành công'), ('PROCESSING_FAILED', 'Xử lý thất bại'), ('CONFIRMED', 'Đã xác nhận'), ('COMPLETED', 'Hoàn thành'), ('CANCELED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
