# Generated by Django 5.2.9 on 2025-12-29 06:13

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_deliveryattempt_reason_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivering_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunding_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', 'Chờ xác nhận'), ('PROCESSING', 'Đang xử lý'), ('PROCESSING_SUCCESS', 'Xử lý thành công'), ('PROCESSING_FAILED', 'Xử lý thất bại'), ('MANUAL_CHECK', 'Kiểm tra thủ công'), ('CONFIRMED', 'Đã xác nhận'), ('DELIVERING', 'Đang giao hàng'), ('DELIVERED', 'Giao thành công'), ('REFUND_REQUESTED', 'Đã gửi yêu cầu hoàn tiền'), ('REFUNDING', 'Đang hoàn tiền'), ('REFUNDED', 'Đã hoàn tiền'), ('COMPLETED', 'Hoàn thành'), ('CANCELED', 'Đã hủy')], default='PENDING', max_length=20, protected=True),
        ),
    ]
