# Generated by Django 5.2.9 on 2026-01-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_canceled_reason_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='district',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
