# Generated by Django 5.2.9 on 2026-01-04 02:38

import django.db.models.deletion
import django_fsm
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_remove_orderaddress_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('txn_ref', models.CharField(max_length=100, unique=True)),
                ('provider_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_code', models.CharField(choices=[('VNPAY', 'Ví VNPAY'), ('MOMO', 'Ví MoMo'), ('COD', 'Thanh toán khi nhận hàng')], default='VNPAY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Đang chờ thanh toán'), ('SUCCESS', 'Thanh toán thành công'), ('FAILED', 'Thanh toán thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=20)),
                ('payment_success_at', models.DateTimeField()),
                ('payment_failed_at', models.DateTimeField()),
                ('payment_refunded_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('payment_url_created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
