# Generated by Django 5.2.9 on 2025-12-17 07:19

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('USER', 'Khách hàng'), ('BOT', 'AI Trợ lý'), ('STAFF', 'Nhân viên hỗ trợ'), ('SYSTEM', 'Hệ thống')], max_length=10)),
                ('content', models.TextField()),
                ('file_attachments', models.JSONField(blank=True, default=list)),
                ('token_usage', models.PositiveIntegerField(default=0)),
                ('user_feedback', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(default='Cuộc hội thoại mới', max_length=255)),
                ('session_type', models.CharField(choices=[('SALES', 'Tư vấn bán hàng'), ('SUPPORT', 'Hỗ trợ kỹ thuật'), ('GENERAL', 'Hỏi đáp chung')], default='SALES', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bot_active', models.BooleanField(default=True, help_text='Nếu False, AI sẽ ngừng trả lời để nhân viên chat')),
                ('needs_human_assistance', models.BooleanField(default=False)),
                ('context_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('interested_products', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'Mới tiếp nhận'), ('processing', 'Đang tư vấn'), ('closed_won', 'Đã chốt đơn'), ('closed_lost', 'Khách hủy/Không mua')], default='new', max_length=20)),
                ('ai_summary', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Mở'), ('IN_PROGRESS', 'Đang xử lý'), ('RESOLVED', 'Đã xong'), ('CLOSED', 'Đóng')], default='OPEN')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='MEDIUM', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_feedback', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image_attachment', models.ImageField(blank=True, null=True, upload_to='ticket_images/')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='ticket_files/')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
