# Generated by Django 5.2.9 on 2025-12-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideo',
            name='variant',
        ),
        migrations.AddField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product'),
            preserve_default=False,
        ),
    ]
