# Generated by Django 5.2.9 on 2025-12-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productvideo_variant_productvideo_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
