# Generated by Django 5.2.9 on 2025-12-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_alt_text_productimage_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
