# Generated by Django 5.2.9 on 2025-12-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
