# Generated by Django 5.2.9 on 2025-12-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productvariant_tax_rate_product_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
