# Generated by Django 5.2.9 on 2025-12-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant_sale_price_alter_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=10000, editable=False, max_digits=15),
            preserve_default=False,
        ),
    ]
