# Generated by Django 5.2.9 on 2025-12-17 07:19

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuilderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CPU', 'Vi xử lý'), ('GPU', 'Card đồ họa'), ('RAM', 'Bộ nhớ trong'), ('STORAGE', 'Ổ cứng'), ('MAINBOARD', 'Bo mạch chủ'), ('PSU', 'Nguồn máy tính'), ('CASE', 'Vỏ máy'), ('COOLING', 'Tản nhiệt')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
